name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test
      - run: docker compose -f tests/functionnal/dependencies/docker-compose.yaml up -d
      - run: docker compose -f tests/functionnal/dependencies/tester-compose.yaml up