name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm test
      - run: docker compose -f tests/functionnal/dependencies/docker-compose.yaml up -d
      - run: docker compose -f tests/functionnal/dependencies/tester-compose.yaml up