name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: |
            pwd/tests/functionnal/dependencies/docker-compose.yaml
            pwd/tests/functionnal/dependencies/tester-compose.yaml
          down-flags: "-d"
      - run: npm ci
      - run: npm test